(function(a){if(String.prototype.trim===a)String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")};if(Array.prototype.reduce===a)Array.prototype.reduce=function(i){if(this===void 0||this===null)throw new TypeError;var k=Object(this),c=k.length>>>0,h=0,l;if(typeof i!="function")throw new TypeError;if(c==0&&arguments.length==1)throw new TypeError;if(arguments.length>=2)l=arguments[1];else{do{if(h in k){l=k[h++];break}if(++h>=c)throw new TypeError;}while(1)}for(;h<c;)h in k&&
(l=i.call(a,l,k[h],h,k)),h++;return l}})();
var Zepto=function(){function a(b){return{}.toString.call(b)=="[object Function]"}function i(b){return b instanceof Object}function k(b){return b instanceof Array}function c(b){return typeof b.length=="number"}function h(b){return b.filter(function(b){return b!==d&&b!==null})}function l(b){return b.replace(/-+(.)?/g,function(b,d){return d?d.toUpperCase():""})}function j(b){return b.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,"-").toLowerCase()}
function f(b){return b.filter(function(b,d,a){return a.indexOf(b)==d})}function t(b){return b in y?y[b]:y[b]=RegExp("(^|\\s)"+b+"(\\s|$)")}function m(b,a){a===d&&C.test(b);a in D||(a="*");var e=D[a];e.innerHTML=""+b;return w.call(e.childNodes)}function o(b,d){b=b||x;b.__proto__=o.prototype;b.selector=d||"";return b}function g(b,e){if(!b)return o();if(e!==d)return g(e).find(b);else if(a(b))return g(r).ready(b);else if(b instanceof o)return b;else{var c;k(b)?c=h(b):G.indexOf(b.nodeType)>=0||b===window?
(c=[b],b=null):C.test(b)?(c=m(b.trim(),RegExp.$1),b=null):c=b.nodeType&&b.nodeType==3?[b]:v(r,b);return o(c,b)}}function q(b,a){return a===d?g(b):g(b).filter(a)}function u(b,d,e,c){return a(d)?d.call(b,e,c):d}function n(b,d,a){var e=b%2?d:d.parentNode;e&&e.insertBefore(a,!b?d.nextSibling:b==1?e.firstChild:b==2?d:null)}function e(b,d){d(b);for(var a in b.childNodes)e(b.childNodes[a],d)}var d,p,v,s,x=[],w=x.slice,r=window.document,z={},y={},A=r.defaultView.getComputedStyle,E={"column-count":1,columns:1,
"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},C=/^\s*<(\w+)[^>]*>/,G=[1,9,11],B=r.createElement("table"),F=r.createElement("tr"),D={tr:r.createElement("tbody"),tbody:B,thead:B,tfoot:B,td:F,th:F,"*":r.createElement("div")},H=/complete|loaded|interactive/,I=/^\.([\w-]+)$/,J=/^#([\w-]+)$/,K=/^[\w-]+$/;g.extend=function(b){objects=w.call(arguments,1);typeof b==="boolean"&&(b=objects[0],objects=w.call(arguments,2));objects.forEach(function(d){for(p in d)b[p]=d[p]});return b};g.qsa=v=function(b,
d){var a;if(b===r&&J.test(d))return(a=b.getElementById(RegExp.$1))&&[a]||[];else{if(I.test(d))a=w.call(b.getElementsByClassName(RegExp.$1));else if(K.test(d))a=w.call(b.getElementsByTagName(d));else try{var e=b.querySelectorAll(d);a=w.call(e)}catch(c){a=[d]}return a}};g.isFunction=a;g.isObject=i;g.isArray=k;g.map=function(b,d){var a,e=[],n;if(c(b))for(n=0;n<b.length;n++)a=d(b[n],n),a!=null&&e.push(a);else for(n in b)a=d(b[n],n),a!=null&&e.push(a);return e.length>0?[].concat.apply([],e):e};g.each=
function(b,d){var a;if(c(b))for(a=0;a<b.length;a++){if(d.call(b[a],a,b[a])===false)break}else for(a in b)if(d.call(b[a],a,b[a])===false)break;return b};g.fn={forEach:x.forEach,reduce:x.reduce,push:x.push,indexOf:x.indexOf,concat:x.concat,map:function(b){return g.map(this,function(d,a){return b.call(d,a,d)})},slice:function(){return g(w.apply(this,arguments))},ready:function(b){H.test(r.readyState)?b(g):r.addEventListener("DOMContentLoaded",function(){b(g)},false);return this},get:function(b){return b===
d?this:this[b]},size:function(){return this.length},remove:function(){return this.each(function(){this.parentNode!=null&&this.parentNode.removeChild(this)})},each:function(b){this.forEach(function(d,a){b.call(d,a,d)});return this},filter:function(b){return g([].filter.call(this,function(d){return d.parentNode&&v(d.parentNode,b).indexOf(d)>=0}))},end:function(){return this.prevObject||g()},andSelf:function(){return this.add(this.prevObject||g())},add:function(b,d){return g(f(this.concat(g(b,d))))},
is:function(b){return this.length>0&&g(this[0]).filter(b).length>0},not:function(b){var e=[];if(a(b)&&b.call!==d)this.each(function(d){b.call(this,d)||e.push(this)});else{var n=typeof b=="string"?this.filter(b):c(b)&&a(b.item)?w.call(b):g(b);this.forEach(function(b){n.indexOf(b)<0&&e.push(b)})}return g(e)},eq:function(b){return b===-1?this.slice(b):this.slice(b,+b+1)},first:function(){var b=this[0];return b&&!i(b)?b:g(b)},last:function(){var b=this[this.length-1];return b&&!i(b)?b:g(b)},find:function(b){var d;
d=this.length==1?v(this[0],b):this.map(function(){return v(this,b)});return g(d)},closest:function(b,d){var a=this[0],e=v(d||r,b);for(e.length||(a=null);a&&e.indexOf(a)<0;)a=a!==d&&a!==r&&a.parentNode;return g(a)},parents:function(b){for(var d=[],a=this;a.length>0;)a=g.map(a,function(b){if((b=b.parentNode)&&b!==r&&d.indexOf(b)<0)return d.push(b),b});return q(d,b)},parent:function(b){return q(f(this.pluck("parentNode")),b)},children:function(b){return q(this.map(function(){return w.call(this.children)}),
b)},siblings:function(b){return q(this.map(function(b,d){return w.call(d.parentNode.children).filter(function(b){return b!==d})}),b)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(b){return this.map(function(){return this[b]})},show:function(){return this.each(function(){this.style.display=="none"&&(this.style.display=null);if(A(this,"").getPropertyValue("display")=="none"){var b=this.style,d=this.nodeName,a,e;z[d]||(a=r.createElement(d),r.body.appendChild(a),e=
A(a,"").getPropertyValue("display"),a.parentNode.removeChild(a),e=="none"&&(e="block"),z[d]=e);b.display=z[d]}})},replaceWith:function(b){return this.each(function(){g(this).before(b).remove()})},wrap:function(b){return this.each(function(){g(this).wrapAll(g(b)[0].cloneNode(false))})},wrapAll:function(b){this[0]&&(g(this[0]).before(b=g(b)),b.append(this));return this},unwrap:function(){this.parent().each(function(){g(this).replaceWith(g(this).children())});return this},hide:function(){return this.css("display",
"none")},toggle:function(b){return(b===d?this.css("display")=="none":b)?this.show():this.hide()},prev:function(){return g(this.pluck("previousElementSibling"))},next:function(){return g(this.pluck("nextElementSibling"))},html:function(b){return b===d?this.length>0?this[0].innerHTML:null:this.each(function(d){var a=this.innerHTML;g(this).empty().append(u(this,b,d,a))})},text:function(b){return b===d?this.length>0?this[0].textContent:null:this.each(function(){this.textContent=b})},attr:function(b,a){var e;
return typeof b=="string"&&a===d?this.length==0?d:b=="value"&&this[0].nodeName=="INPUT"?this.val():!(e=this[0].getAttribute(b))&&b in this[0]?this[0][b]:e:this.each(function(d){if(i(b))for(p in b)this.setAttribute(p,b[p]);else this.setAttribute(b,u(this,a,d,this.getAttribute(b)))})},removeAttr:function(b){return this.each(function(){this.removeAttribute(b)})},data:function(b,d){return this.attr("data-"+b,d)},val:function(b){return b===d?this.length>0?this[0].value:null:this.each(function(d){this.value=
u(this,b,d,this.value)})},offset:function(){if(this.length==0)return null;var b=this[0].getBoundingClientRect();return{left:b.left+window.pageXOffset,top:b.top+window.pageYOffset,width:b.width,height:b.height}},css:function(b,a){if(a===d&&typeof b=="string")return this.length==0?d:this[0].style[l(b)]||A(this[0],"").getPropertyValue(b);var e="";for(p in b)e+=j(p)+":"+(typeof b[p]=="number"&&!E[j(p)]?b[p]+"px":b[p])+";";typeof b=="string"&&(e=j(b)+":"+(typeof a=="number"&&!E[j(b)]?a+"px":a));return this.each(function(){this.style.cssText+=
";"+e})},index:function(b){return b?this.indexOf(g(b)[0]):this.parent().children().indexOf(this[0])},hasClass:function(b){return this.length<1?false:t(b).test(this[0].className)},addClass:function(b){return this.each(function(d){s=[];var a=this.className;u(this,b,d,a).split(/\s+/g).forEach(function(b){g(this).hasClass(b)||s.push(b)},this);s.length&&(this.className+=(a?" ":"")+s.join(" "))})},removeClass:function(b){return this.each(function(a){if(b===d)return this.className="";s=this.className;u(this,
b,a,s).split(/\s+/g).forEach(function(b){s=s.replace(t(b)," ")});this.className=s.trim()})},toggleClass:function(b,a){return this.each(function(e){e=u(this,b,e,this.className);(a===d?!g(this).hasClass(e):a)?g(this).addClass(e):g(this).removeClass(e)})}};"filter,add,not,eq,first,last,find,closest,parents,parent,children,siblings".split(",").forEach(function(b){var d=g.fn[b];g.fn[b]=function(){var b=d.apply(this,arguments);b.prevObject=this;return b}});["width","height"].forEach(function(b){g.fn[b]=
function(a){var e,c=b.replace(/./,function(b){return b[0].toUpperCase()});return a===d?this[0]==window?window["inner"+c]:this[0]==r?r.documentElement["offset"+c]:(e=this.offset())&&e[b]:this.each(function(d){var e=g(this);e.css(b,u(this,a,d,e[b]()))})}});["after","prepend","before","append"].forEach(function(b,d){g.fn[b]=function(b){var a=i(b)?b:m(b);if(!("length"in a)||a.nodeType)a=[a];if(a.length<1)return this;var c=this.length,p=c>1,f=d<2;return this.each(function(b,g){for(var s=0;s<a.length;s++){var v=
a[f?a.length-s-1:s];e(v,function(b){b.nodeName!=null&&b.nodeName.toUpperCase()==="SCRIPT"&&(!b.type||b.type==="text/javascript")&&window.eval.call(window,b.innerHTML)});p&&b<c-1&&(v=v.cloneNode(true));n(d,g,v)}})};g.fn[d%2?b+"To":"insert"+(d?"Before":"After")]=function(d){g(d)[b](this);return this}});o.prototype=g.fn;return g}();window.Zepto=Zepto;"$"in window||(window.$=Zepto);
(function(a){function i(a,e,d,c){e=k(e);if(e.ns)var f=RegExp("(?:^| )"+e.ns.replace(" "," .* ?")+"(?: |$)");return(t[a._zid||(a._zid=m++)]||[]).filter(function(a){return a&&(!e.e||a.e==e.e)&&(!e.ns||f.test(a.ns))&&(!d||a.fn==d)&&(!c||a.sel==c)})}function k(a){a=(""+a).split(".");return{e:a[0],ns:a.slice(1).sort().join(" ")}}function c(c,e,d){a.isObject(c)?a.each(c,d):c.split(/\s/).forEach(function(a){d(a,e)})}function h(n,e,d,p,f){var g=n._zid||(n._zid=m++),j=t[g]||(t[g]=[]);c(e,d,function(d,e){var c=
f&&f(e,d),g=c||e,h=function(a){var d=g.apply(n,[a].concat(a.data));d===false&&a.preventDefault();return d},c=a.extend(k(d),{fn:e,proxy:h,sel:p,del:c,i:j.length});j.push(c);n.addEventListener&&n.addEventListener(c.e,h,false)})}function l(a,e,d,f){var g=a._zid||(a._zid=m++);c(e||"",d,function(d,e){i(a,d,e,f).forEach(function(d){delete t[g][d.i];a.removeEventListener(d.e,d.proxy,false)})})}function j(c){var e=a.extend({originalEvent:c},c);a.each(u,function(a,f){e[a]=function(){this[f]=g;return c[a].apply(c,
arguments)};e[f]=q});return e}function f(a){if(!("defaultPrevented"in a)){a.defaultPrevented=false;var e=a.preventDefault;a.preventDefault=function(){this.defaultPrevented=true;e.call(this)}}}var t={},m=1,o={};o.click=o.mousedown=o.mouseup=o.mousemove="MouseEvents";a.event={add:h,remove:l};a.fn.bind=function(a,e){return this.each(function(){h(this,a,e)})};a.fn.unbind=function(a,e){return this.each(function(){l(this,a,e)})};a.fn.one=function(a,e){return this.each(function(d,c){h(this,a,e,null,function(a,
d){return function(){var e=a.apply(c,arguments);l(c,d,a);return e}})})};var g=function(){return true},q=function(){return false},u={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};a.fn.delegate=function(c,e,d){return this.each(function(f,g){h(g,e,d,c,function(d){return function(e){var f,p=a(e.target).closest(c,g).get(0);if(p)return f=a.extend(j(e),{currentTarget:p,liveFired:g}),d.apply(p,[f].concat([].slice.call(arguments,
1)))}})})};a.fn.undelegate=function(a,e,d){return this.each(function(){l(this,e,d,a)})};a.fn.live=function(c,e){a(document.body).delegate(this.selector,c,e);return this};a.fn.die=function(c,e){a(document.body).undelegate(this.selector,c,e);return this};a.fn.on=function(c,e,d){return e===void 0||a.isFunction(e)?this.bind(c,e):this.delegate(e,c,d)};a.fn.off=function(c,e,d){return e===void 0||a.isFunction(e)?this.unbind(c,e):this.undelegate(e,c,d)};a.fn.trigger=function(c,e){typeof c=="string"&&(c=a.Event(c));
f(c);c.data=e;return this.each(function(){if(this.dispatchEvent)try{this.dispatchEvent(c)}catch(a){}})};a.fn.triggerHandler=function(c,e){var d,f;this.each(function(g,h){d=j(typeof c=="string"?a.Event(c):c);d.data=e;d.target=h;a.each(i(h,c.type||c),function(a,e){f=e.proxy(d);if(d.isImmediatePropagationStopped())return false})});return f};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout change select keydown keypress keyup error".split(" ").forEach(function(c){a.fn[c]=
function(a){return this.bind(c,a)}});["focus","blur"].forEach(function(c){a.fn[c]=function(a){if(a)this.bind(c,a);else if(this.length)try{this.get(0)[c]()}catch(d){}return this}});a.Event=function(a,e){var d=document.createEvent(o[a]||"Events"),c=true;if(e)for(var f in e)f=="bubbles"?c=!!e[f]:d[f]=e[f];d.initEvent(a,c,true,null,null,null,null,null,null,null,null,null,null,null,null);return d}})(Zepto);
(function(a){function i(a){var c=this.os={},h=this.browser={},i=a.match(/WebKit\/([\d.]+)/),j=a.match(/(Android)\s+([\d.]+)/),f=a.match(/(iPad).*OS\s([\d_]+)/),t=!f&&a.match(/(iPhone\sOS)\s([\d_]+)/),m=a.match(/(webOS|hpwOS)[\s\/]([\d.]+)/),o=m&&a.match(/TouchPad/),a=a.match(/(BlackBerry).*Version\/([\d.]+)/);if(i)h.version=i[1];h.webkit=!!i;if(j)c.android=true,c.version=j[2];if(t)c.ios=true,c.version=t[2].replace(/_/g,"."),c.iphone=true;if(f)c.ios=true,c.version=f[2].replace(/_/g,"."),c.ipad=true;
if(m)c.webos=true,c.version=m[2];if(o)c.touchpad=true;if(a)c.blackberry=true,c.version=a[2]}i.call(a,navigator.userAgent);a.__detect=i})(Zepto);
(function(a,i){var k="",c,h=window.document.createElement("div"),l=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i;a.each({Webkit:"webkit",Moz:"",O:"o",ms:"MS"},function(a,f){if(h.style[a+"TransitionProperty"]!==i)return k="-"+a.toLowerCase()+"-",c=f,false});a.fx={off:c===i&&h.style.transitionProperty===i,cssPrefix:k,transitionEnd:c?c+"TransitionEnd":"transitionend",animationEnd:c?c+"AnimationEnd":"animationend"};a.fn.animate=function(c,f,h,i){if(a.isObject(f))h=f.easing,
i=f.complete,f=f.duration;f&&(f/=1E3);return this.anim(c,f,h,i)};a.fn.anim=function(c,f,h,m){var o,g={},q,u=this,n,e=a.fx.transitionEnd;f===i&&(f=0.4);a.fx.off&&(f=0);if(typeof c=="string")g[k+"animation-name"]=c,g[k+"animation-duration"]=f+"s",e=a.fx.animationEnd;else{for(q in c)l.test(q)?(o||(o=[]),o.push(q+"("+c[q]+")")):g[q]=c[q];o&&(g[k+"transform"]=o.join(" "));a.fx.off||(g[k+"transition"]="all "+f+"s "+(h||""))}n=function(){var d={};d[k+"transition"]=d[k+"animation-name"]="none";a(this).css(d);
m&&m.call(this)};if(f>0)this.one(e,n);setTimeout(function(){u.css(g);f<=0&&setTimeout(function(){u.each(function(){n.call(this)})},0)},0);return this};h=null})(Zepto);
(function(a){function i(c,d,f,h){if(c.global)return c=d||g,f=a.Event(f),a(c).trigger(f,h),!f.defaultPrevented}function k(c){c.global&&a.active++===0&&i(c,null,"ajaxStart")}function c(a,d){var c=d.context;if(d.beforeSend.call(c,a,d)===false||i(d,c,"ajaxBeforeSend",[a,d])===false)return false;i(d,c,"ajaxSend",[a,d])}function h(a,d,c){var f=c.context;c.success.call(f,a,"success",d);i(c,f,"ajaxSuccess",[d,c,a]);j("success",d,c)}function l(a,d,c,f){var g=f.context;f.error.call(g,c,d,a);i(f,g,"ajaxError",
[c,f,a]);j(d,c,f)}function j(c,d,f){var g=f.context;f.complete.call(g,d,c);i(f,g,"ajaxComplete",[d,f]);f.global&&!--a.active&&i(f,null,"ajaxStop")}function f(){}function t(c,d,f,g){var h=a.isArray(d);a.each(d,function(d,i){g&&(d=f?g:g+"["+(h?"":d)+"]");!g&&h?c.add(i.name,i.value):(f?a.isArray(i):o(i))?t(c,i,f,d):c.add(d,i)})}var m=0,o=a.isObject,g=window.document,q,u;a.active=0;a.ajaxJSONP=function(c){var d="jsonp"+ ++m,i=g.createElement("script"),l={abort:function(){a(i).remove();d in window&&(window[d]=
f);j(l,c,"abort")}},s;window[d]=function(f){clearTimeout(s);a(i).remove();delete window[d];h(f,l,c)};i.src=c.url.replace(/=\?/,"="+d);a("head").append(i);c.timeout>0&&(s=setTimeout(function(){l.abort();j(l,c,"timeout")},c.timeout));return l};a.ajaxSettings={type:"GET",beforeSend:f,success:f,error:f,complete:f,context:null,global:true,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript",json:"application/json",xml:"application/xml, text/xml",html:"text/html",
text:"text/plain"},xhrFields:{},crossDomain:false,timeout:0};a.ajax=function(e){var d=a.extend({},e||{});for(q in a.ajaxSettings)d[q]===void 0&&(d[q]=a.ajaxSettings[q]);k(d);if(!d.crossDomain)d.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(d.url)&&RegExp.$2!=window.location.host;if(/=\?/.test(d.url))return a.ajaxJSONP(d);if(!d.url)d.url=window.location.toString();if(d.data&&!d.contentType)d.contentType="application/x-www-form-urlencoded";if(o(d.data))d.data=a.param(d.data);if(d.type.match(/get/i)&&d.data)e=
d.data,d.url.match(/\?.*=/)?e="&"+e:e[0]!="?"&&(e="?"+e),d.url+=e;var g=d.accepts[d.dataType],e={},i=/^([\w-]+:)\/\//.test(d.url)?RegExp.$1:window.location.protocol,j=a.ajaxSettings.xhr(),m;d.crossDomain||(e["X-Requested-With"]="XMLHttpRequest");g&&(e.Accept=g);d.headers=a.extend(e,d.headers||{});j.onreadystatechange=function(){if(j.readyState==4){clearTimeout(m);var a,c=false;if(j.status>=200&&j.status<300||j.status==0&&i=="file:"){if(g=="application/json"&&!/^\s*$/.test(j.responseText))try{a=JSON.parse(j.responseText)}catch(e){c=
e}else a=j.responseText;c?l(c,"parsererror",j,d):h(a,j,d)}else l(null,"error",j,d)}};j.open(d.type,d.url,true);if(d.xhrFields)for(var t in d.xhrFields)j[t]=d.xhrFields[t];if(d.contentType)d.headers["Content-Type"]=d.contentType;for(u in d.headers)j.setRequestHeader(u,d.headers[u]);if(c(j,d)===false)return j.abort(),false;d.timeout>0&&(m=setTimeout(function(){j.onreadystatechange=f;j.abort();l(null,"timeout",j,d)},d.timeout));if(d.data==="")d.data=null;j.send(d.data);return j};a.get=function(c,d){return a.ajax({url:c,
success:d})};a.post=function(c,d,f,g){a.isFunction(d)&&(g=g||f,f=d,d=null);return a.ajax({type:"POST",url:c,data:d,success:f,dataType:g})};a.getJSON=function(c,d){return a.ajax({url:c,success:d,dataType:"json"})};a.fn.load=function(c,d){if(!this.length)return this;var f=this,h=c.split(/\s/),j;h.length>1&&(c=h[0],j=h[1]);a.get(c,function(c){f.html(j?a(g.createElement("div")).html(c).find(j).html():c);d&&d.call(f)});return this};var n=encodeURIComponent;a.param=function(a,d){var c=[];c.add=function(a,
d){this.push(n(a)+"="+n(d))};t(c,a,d);return c.join("&").replace("%20","+")}})(Zepto);
(function(a){a.fn.serializeArray=function(){var i=[],k;a(Array.prototype.slice.call(this.get(0).elements)).each(function(){k=a(this);var c=k.attr("type");!this.disabled&&c!="submit"&&c!="reset"&&c!="button"&&(c!="radio"&&c!="checkbox"||this.checked)&&i.push({name:k.attr("name"),value:k.val()})});return i};a.fn.serialize=function(){var a=[];this.serializeArray().forEach(function(k){a.push(encodeURIComponent(k.name)+"="+encodeURIComponent(k.value))});return a.join("&")};a.fn.submit=function(i){i?this.bind("submit",
i):this.length&&(i=a.Event("submit"),this.eq(0).trigger(i),i.defaultPrevented||this.get(0).submit());return this}})(Zepto);
(function(a){function i(a,c,h,i){var l=Math.abs(a-c),g=Math.abs(h-i);return l>=g?a-c>0?"Left":"Right":h-i>0?"Up":"Down"}function k(){c.last&&Date.now()-c.last>=l&&(a(c.target).trigger("longTap"),c={})}var c={},h,l=750;a(document).ready(function(){a(document.body).bind("touchstart",function(a){var f=Date.now(),i=f-(c.last||f);c.target="tagName"in a.touches[0].target?a.touches[0].target:a.touches[0].target.parentNode;h&&clearTimeout(h);c.x1=a.touches[0].pageX;c.y1=a.touches[0].pageY;if(i>0&&i<=250)c.isDoubleTap=
true;c.last=f;setTimeout(k,l)}).bind("touchmove",function(a){c.x2=a.touches[0].pageX;c.y2=a.touches[0].pageY}).bind("touchend",function(){c.isDoubleTap?(a(c.target).trigger("doubleTap"),c={}):c.x2>0||c.y2>0?((Math.abs(c.x1-c.x2)>30||Math.abs(c.y1-c.y2)>30)&&a(c.target).trigger("swipe")&&a(c.target).trigger("swipe"+i(c.x1,c.x2,c.y1,c.y2)),c.x1=c.x2=c.y1=c.y2=c.last=0):"last"in c&&(h=setTimeout(function(){h=null;a(c.target).trigger("tap");c={}},250))}).bind("touchcancel",function(){c={}})});"swipe,swipeLeft,swipeRight,swipeUp,swipeDown,doubleTap,tap,longTap".split(",").forEach(function(c){a.fn[c]=
function(a){return this.bind(c,a)}})})(Zepto);(function(a){function i(f,i){var l=f[j],l=l&&c[l];return i===void 0?l||k(f):l&&l[i]||h.call(a(f),i)}function k(a,h,i){a=a[j]||(a[j]=++l);a=c[a]||(c[a]={});h!==void 0&&(a[h]=i);return a}var c={},h=a.fn.data,l=a.uuid=+new Date,j=a.expando="Zepto"+l;a.fn.data=function(c,h){return h===void 0?this.length==0?void 0:i(this[0],c):this.each(function(j){k(this,c,a.isFunction(h)?h.call(this,j,i(this,c)):h)})}})(Zepto);
(function(a){a.expr={":":{}};a.support={};a.fn.clone=function(){var c=a();this.each(function(){c.push(this.cloneNode(true))});return c};["Left","Top"].forEach(function(c,h){function i(a){return a&&typeof a==="object"&&"setInterval"in a?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var j="scroll"+c;a.fn[j]=function(c){var k,m;if(c===void 0){k=this[0];return!k?null:(m=i(k))?"pageXOffset"in m?m[h?"pageYOffset":"pageXOffset"]:m.document.documentElement[j]||m.document.body[j]:k[j]}this.each(function(){if(m=
i(this)){var k=!h?c:a(m).scrollLeft(),g=h?c:a(m).scrollTop();m.scrollTo(k,g)}else this[j]=c})}});["width","height"].forEach(function(c){var h=c.replace(/./,function(a){return a[0].toUpperCase()});a.fn["outer"+h]=function(a){var h=this;if(h){var f=h[c]();({width:["left","right"],height:["top","bottom"]})[c].forEach(function(c){a&&(f+=parseInt(h.css("margin-"+c),10))});return f}else return null}});a.proxy=function(c,h){if(typeof h==="string")var i=c[h],h=c,c=i;if(a.isFunction(c)){var j=Array.prototype.slice.call(arguments,
2),i=function(){return c.apply(h,j.concat(Array.prototype.slice.call(arguments)))};i.guid=c.guid=c.guid||i.guid||a.guid++;return i}};var i=String.prototype.trim;a.trim=function(a,h){if(!h&&i)return i.call(a);h=defaultToWhiteSpace(h);return a.replace(RegExp("^["+h+"]+|["+h+"]+$","g"),"")};a.fn.preload=function(){this.each(function(){a("<img/>")[0].src=this})};var k=/^(?:body|html)$/i;a.fn.position=function(){if(!this[0])return null;var c=this[0],h=this.offsetParent(),i=this.offset(),j=k.test(h[0].nodeName)?
{top:0,left:0}:h.offset();i.top-=parseFloat(a(c).css("margin-top"))||0;i.left-=parseFloat(a(c).css("margin-left"))||0;j.top+=parseFloat(a(h[0]).css("border-top-width"))||0;j.left+=parseFloat(a(h[0]).css("border-left-width"))||0;return{top:i.top-j.top,left:i.left-j.left}};a.fn.offsetParent=function(){var c=a();this.each(function(){for(var h=this.offsetParent||document.body;h&&!k.test(h.nodeName)&&a(h).css("position")==="static";)h=h.offsetParent;c.push(h)});return c};Event.prototype.isDefaultPrevented=
function(){return this.defaultPrevented}})(Zepto);
